spring:
  ai:
    model:
      chat: none
    ollama:
      chat:
        enabled: false
    google:
      genai:
        chat:
          enabled: false
  application:
    name: nbot
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nbot}
    username: ${SPRING_DATASOURCE_USERNAME:nbot}
    password: ${SPRING_DATASOURCE_PASSWORD:nbot_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


nbot:
  telegram:
    enabled: true
    allowed-users: ${ALLOWED_USERS:}
    telegram-bot-token: ${TELEGRAM_BOT_TOKEN:}
    dashboard-url: ${DASHBOARD_URL:http://localhost:8080}
  qbittorrent:
    url: ${QBITTORRENT_URL:http://localhost:8090}
    username: ${QBITTORRENT_USERNAME:admin}
    password: ${QBITTORRENT_PASSWORD:adminadmin}
  actual-budget:
    url: ${ACTUAL_BUDGET_URL:http://localhost:5007/v1}
    api-key: ${ACTUAL_BUDGET_API_KEY:}
    sync-id: ${ACTUAL_BUDGET_SYNC_ID:}
    encryption-password: ${ACTUAL_BUDGET_ENCRYPTION_PASSWORD:}
    default-account-id: ${ACTUAL_BUDGET_DEFAULT_ACCOUNT_ID:}
    internal-accounts: ${ACTUAL_BUDGET_INTERNAL_ACCOUNTS:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops

logging:
  level:
      dev.naguiar: DEBUG

---
spring:
  config:
    activate:
      on-profile: gemini
  ai:
    model:
      chat: google-genai
    ollama:
      chat:
        enabled: false
    google:
      genai:
        chat:
          enabled: true
        api-key: ${GEMINI_API_KEY:}

---
spring:
  config:
    activate:
      on-profile: ollama
  ai:
    model:
      chat: ollama
    google:
      genai:
        chat:
          enabled: false
    ollama:
      chat:
        enabled: true
        options:
          model: llama3.1:latest
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
