spring:
  application:
    name: nbot
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nbot}
    username: ${SPRING_DATASOURCE_USERNAME:nbot}
    password: ${SPRING_DATASOURCE_PASSWORD:nbot_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


nbot:
  security:
    allowed-users: ${ALLOWED_USERS:}
    telegram-bot-token: ${TELEGRAM_BOT_TOKEN:}
  qbittorrent:
    url: ${QBITTORRENT_URL:http://localhost:8080}
    username: ${QBITTORRENT_USERNAME:admin}
    password: ${QBITTORRENT_PASSWORD:adminadmin}

logging:
  level:
      dev.naguiar: DEBUG

---
spring:
  config:
    activate:
      on-profile: gemini
  ai:
    model:
      chat: google-genai
    ollama:
      chat:
        enabled: false
    google:
      genai:
        chat:
          enabled: true
        api-key: ${GEMINI_API_KEY:}

---
spring:
  config:
    activate:
      on-profile: ollama
  ai:
    model:
      chat: ollama
    google:
      genai:
        chat:
          enabled: false
    ollama:
      chat:
        enabled: true
        options:
          model: llama3.1
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
