apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nbot.fullname" . }}
  labels:
    {{- include "nbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.config.geminiApiKey | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  QBITTORRENT_PASSWORD: {{ .Values.qbittorrent.password | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
